DROP TABLE IF EXISTS store_order_items CASCADE;
DROP TABLE IF EXISTS store_orders CASCADE;
DROP TABLE IF EXISTS store_products CASCADE;
DROP TABLE IF EXISTS analytics_batches CASCADE;
DROP TABLE IF EXISTS ticket_sequences CASCADE;
DROP TABLE IF EXISTS registration_sequences CASCADE;
DROP TABLE IF EXISTS admin_email_deliveries CASCADE;
DROP TABLE IF EXISTS form_campaign_deliveries CASCADE;
DROP TABLE IF EXISTS approval_requests CASCADE;
DROP TABLE IF EXISTS admin_notifications CASCADE;

ALTER TABLE IF EXISTS testimonials DROP COLUMN IF EXISTS approved_at;
ALTER TABLE IF EXISTS testimonials DROP COLUMN IF EXISTS approved_by_email;
ALTER TABLE IF EXISTS testimonials DROP COLUMN IF EXISTS approved_by_name;
ALTER TABLE IF EXISTS testimonials DROP COLUMN IF EXISTS approved_by_id;

ALTER TABLE IF EXISTS events DROP COLUMN IF EXISTS approved_at;
ALTER TABLE IF EXISTS events DROP COLUMN IF EXISTS approved_by_email;
ALTER TABLE IF EXISTS events DROP COLUMN IF EXISTS approved_by_name;
ALTER TABLE IF EXISTS events DROP COLUMN IF EXISTS approved_by_id;
ALTER TABLE IF EXISTS events DROP COLUMN IF EXISTS is_approved;
