DROP INDEX IF EXISTS idx_attendance_records_session_active;
DROP INDEX IF EXISTS idx_attendance_sessions_date_active;
DROP INDEX IF EXISTS idx_form_submissions_form_created;
DROP TABLE IF EXISTS analytics_events;
DROP INDEX IF EXISTS idx_analytics_batches_expires_at;
ALTER TABLE analytics_batches DROP COLUMN IF EXISTS expires_at;
DROP INDEX IF EXISTS idx_analytics_batches_batch_id_unique;
CREATE INDEX IF NOT EXISTS idx_analytics_batches_batch_id ON analytics_batches(batch_id);
DROP INDEX IF EXISTS idx_events_category_event_date;
DROP INDEX IF EXISTS idx_events_event_date;
DROP TRIGGER IF EXISTS trg_events_sync_native_date ON events;
DROP FUNCTION IF EXISTS sync_event_native_date();
ALTER TABLE events DROP COLUMN IF EXISTS event_date;
